# Generated by Django 5.0.6 on 2026-09-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=32)),
                ('row_number', models.IntegerField()),
                ('issue', models.CharField(max_length=255)),
                ('raw_row', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('record_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location_id', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('value_raw', models.CharField(blank=True, max_length=64)),
                ('event_date_raw', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['location_id'], name='reconciler__locatio_3415fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('entry_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('record_ref_raw', models.CharField(blank=True, max_length=64)),
                ('record_ref_normalized', models.CharField(blank=True, db_index=True, max_length=64)),
                ('location_id', models.CharField(blank=True, max_length=64)),
                ('value_raw', models.CharField(blank=True, max_length=64)),
                ('entry_date_raw', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['record_ref_normalized'], name='reconciler__record__384de3_idx')],
            },
        ),
    ]
